fix(monitor): replace with newer ubuntu image
something got this image broken and we can't get it's
metadata

```
   File ".../sdcm/utils/aws_utils.py", line 360, in ec2_ami_get_root_device_name
     if image.root_device_name:
   File ".../site-packages/boto3/resources/factory.py", line 386, in property_loader
     return self.meta.data.get(name)
AttributeError: 'NoneType' object has no attribute 'get'
```

replacing it with newer working image

(cherry picked from commit 818882db62108ca2ea94a4186d0ebecb00c86532)