fix(LongevityOperatorMultiTenantTest): support new generic test_duration
in #5398 new configuration option to set the test duration
were introduced, and broke the k8s multi-tanent longevity like this:

```
AttributeError: 'TenantForLongevityTest-2' object has no attribute '_stress_duration'.
  Did you mean: 'test_duration'?
```

this would call the same method to get those parameters initilized