fix(longevity): get table for 'add_drop_column'
If run disrupt_add_remove_dc nemesis in parallel to the disrupt_add_drop_column one then we can
get following error:

  KeyError: 'keyspace_new_dc'

It is caused by the concurrency of a new keyspace addition (disrupt_add_remove_dc nemesis)
and driver session update in addition to the unsafe coding assuming driver's session
(disrupt_add_drop_column nemesis) knows about that newly added keyspace.
Another possible problem: new added keyspace was dropped in exacly time when we run
describe of the table.

Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/7240