fix(get_any_ks_cf_list): return keyspaces and tables quoted if needed
PR #6897 handled calls to cqlsh to keep the quotes, but we do
have other places when we supply quoted identifiers and it
might break like the following:

```
Executing CQL 'CREATE INDEX standard1_c4_nemesis ON 100gb_sizetiered.standard1("C4")' ...
...
cassandra.protocol.SyntaxException: <Error from server: code=2000 [Syntax
error in CQL query] message="line 1:37 no viable alternative at input '100'">
```

Fixes: #6790
(cherry picked from commit 814a7fa05b51705425ebb68613b27de9a2c9dc42)