fix(k8s): make static loaders work
With merge of the [1] PR the static loaders became broken with the
following error:

  File "sdcm/cluster_k8s/__init__.py", line 3140, in add_nodes
    self.k8s_clusters[current_dc_idx].debug(
  AttributeError: 'EksCluster' object has no attribute 'debug'

So, fix it by using missing "log" attr.

[1] https://github.com/scylladb/scylla-cluster-tests/pull/6773