fix(ParallelObject): remove timeout exception
this branch of the code, just add all of the parallel objects
into the exception, and makes the outcome unclear, cause you
can't know which part is failing

```
concurrent.futures._base.TimeoutError: when running on: [
   functools.partial(<bound method BaseNode.run_nodetool of <...>>, sub_cmd='repair',
                     warning_event_on_exception=(<class 'Exception'>,), retry=0),
   functools.partial(<bound method Nemesis._call_disrupt_func_after_expression_logged of <...>>,
                     log_follower=<...>, disrupt_func=<bound method Nemesis.reboot_node of <...>>,
                     disrupt_func_kwargs={'target_node': <...>, 'hard': True, 'verify_ssh': True},
                     delay=1)]
```

Removing this code path, would end up with the regualr exception
in the case of failed parallal thread, and would should the backtrace of each
it would be a bit more lengthly, but with clearer information
on which part of the parallel had failed/timeoutd