fix(remote_logger): rework SSH-based remote loggers
Main driver for this rework are false failures of some nemeses in ScyllaDB Cloud
longevities which shutdown nodes. Like:

Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 69, in wait_for
res = retry(func, **kwargs)
File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
do = self.iter(retry_state=retry_state)
File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 360, in iter
raise retry_exc.reraise()
File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 194, in reraise
raise self
tenacity.RetryError: RetryError[<Future at 0x7f55642bcfa0 state=finished returned bool>]
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/decorators.py", line 26, in wrapper
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/remote_logger.py", line 120, in _journal_thread
self._wait_ssh_up(verbose=False)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/remote_logger.py", line 145, in _wait_ssh_up
super()._wait_ssh_up(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/remote_logger.py", line 128, in _wait_ssh_up
wait.wait_for(func=self._remoter.is_up, step=10, text=text, timeout=timeout, throw_exc=True)
File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 80, in wait_for
raise WaitForTimeoutError(err) from ex
sdcm.wait.WaitForTimeoutError: Wait for: is_up: timeout - 500 seconds - expired

To fix this problem:

- Use termination event in ._journal_thread()
- Introduce checks for readiness for retrieve logs: ._is_ready_for_retrieve() methods
- Don't use wait_for() for additional implicit waiting loops inside ._journal_thread()

Also improve code quality by:

- Add type annotations
- Use ellipsis instead of pass for abstract methods
- Add _remoter property
- Remove redundant .node attribute (use ._node instead)
- Use kwargs as much as possible
- Use uppercase for constants
- Use cached_property for properties which return static values
- Remove redundant abstract class NodeLoggerBase
- Make SSHScyllaFileLogger a child of SSHGeneralFileLogger
- Remove code duplication and use correct parameter names in CSHDRFileLogger