fix(perf-regression-report): broken casue of cdc stress check
* fallback to None was breaking the code:
```
 Traceback (most recent call last):
   File ".../sdcm/tester.py", line 2946, in check_regression
     results_analyzer.check_regression(self._test_id, is_gce,
   File ".../sdcm/results_analyze/__init__.py", line 588, in check_regression
     query = self._query_filter(doc, is_gce, use_wide_query, lastyear)
   File ".../sdcm/results_analyze/__init__.py", line 526, in _query_filter
     elif "cdc" in test_doc['_source']['test_details'].get('sub_type'):
 TypeError: argument of type 'NoneType' is not iterable
```

* fix the email_results_file location, it's now inside the logdir
  and not at SCT root folder