fix(cluster_docker): wrong path to build context
since build context path was base on `scylla_linux_distro`
which can be: `centos` or `ubuntu-focal`, hence we need to split it.

default `scylla_linux_distro` was changed `ubuntu-focal`
and since then the docker backend was failing like this:

```
TypeError: You must specify a directory to build in path
```