fix(upgrade_test): handle uuid sstable identifier on upgradesstable
since scylladb/scylladb/pull/13932 sstable identifier are
not numbers, and the regex we were using in upgradesstable procudure
assumed they are.

failing like the following:
```
AssertionError: Failed to upgrade the sstable format [False, False, False, False]
```

Ref: https://github.com/scylladb/scylladb/pull/13932