fix(es-upload): reduce amount of data in docs we uplaod to ES
Running performance tests we write lots of data to ElasticSearch
and pretty often get following error which fails test runs:

    elasticsearch.exceptions.RequestError: RequestError(
        400,
        'illegal_argument_exception',
        'Limit of total fields [1000] has been exceeded')

It happens because in some cases when we gather sysctl configs from
DB nodes we get hundreds of records for each node.
And in summary it exceeds 1000 of keys in the data we write.
So, update the code where we gather sysctls removing some huge sets
of data which are unlikely to be used by us.