fix(create role): fix role name in test_workload_types
It is not allowed to create role/service level with name 'batch'.
It cause to query failure with error:

cassandra.protocol.SyntaxException: <Error from server: code=2000 [Syntax error in CQL query]
message=line 1:26 no viable alternative at input 'batch'

This word is reserved for workload type.

(cherry picked from commit d5af5aa54d4644b0e87d406de9d94842afa0887d)