fix(argus): properly check the node type
Use 'node_type' attr of node objects to detect their type instead of
using 'instance_name' one.
It will allow to avoid following error on K8S backends:

  > Traceback (most recent call last):
  >   File "%project-path%/sdcm/cluster.py", line 328, in update_shards_in_argus
  >     shards = self.scylla_shards if "db-node" in self.instance_name else self.cpu_cores
  >   File "%project-path%/sdcm/cluster_k8s/__init__.py", line 2014, in instance_name
  >     return self.node_name
  >   File "/usr/local/lib/python3.10/functools.py", line 970, in __get__
  >     val = self.func(instance)
  >   File "%project-path%/sdcm/cluster_k8s/__init__.py", line 2010, in node_name
  >     return self._pod.spec.node_name
  > AttributeError: 'NoneType' object has no attribute 'spec'
  > Encountered an unhandled exception while interacting with Argus \
    < t:2023-03-30 14:15:50,232 f:cluster.py      l:332  c:sdcm.cluster \
      p:ERROR > Encountered an unhandled exception while interacting with Argus