fix(nemesis): init new nodes must set them as seeds
since #6136 we have been testing our clusters
like all nodes are seeds (since Scylla is now
"seedless" for quite some time), but when running
`disrupt_grow_shrink_cluster` for the 5th time,
we start failing with error:
```
AssertionError: We should have at least one selected seed by now
```

this fix will also be fixing all other nemeses
that do add new nodes to the cluster, when running
for quite some time, probability of hitting it on
regular replace node operations is smaller, since
this nemesis runs 3 times add new node in each loop
iteration.