fix(snapshot nemesis): check status code instead of stderr
Since a recent change in scylla-java-tools, we are seeing those
failures below, the nemesis is wrong checking the stderr, which
could have all kind of things printed in it doesn't mean the
command failed.

status code is check by default by `run_nodetool()`

```
Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 1910, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 2124, in disrupt
    self.call_random_disrupt_method()
  File "/sct/sdcm/nemesis.py", line 656, in call_random_disrupt_method
    disrupt_method()
  File "/sct/sdcm/nemesis.py", line 1366, in disrupt_snapshot_operations
    self.tester.fail(result.stderr)
  File "/usr/lib64/python3.6/unittest/case.py", line 687, in fail
    raise self.failureException(msg)
AssertionError: mkdir: cannot create directory ‘/opt/scylladb/share/cassandra/logs’:
Permission denied
```