fix(longevity-10gb-3h-gce): specify proper region
Pipeline that is used by "longevity-10gb-3h-gce" CI job doesn't
specify region for GCE backend and it leads to the situation where
default name from AWS backend gets picked up.
It leads to the following error:

    AssertionError: only `us-east1' region is supported

So, specify correct and supported GCE backend to make this job work.