fix(ycsb_thread): remove exception logging on uninit metrics
seem like a bug in YCSB print some of the metrics as null or something
like that:

lot of the metric cause to lot of those exceptions
```
Traceback (most recent call last):
  File "/sct/sdcm/ycsb_thread.py", line 93, in run
    value = float(value) / 1000.0
ValueError: could not convert string to float: '�'
value isn't a number, default to 0
```

this commit is remove this log line, we are fine without see this
at the stdout

Ref: https://trello.com/c/6ryqzL2q