fix(artifact-centos8-arm): update to lastet AMI
the AMI we had was deprecated, hence the metadata
retrvial of it fails like the following:
```
Traceback (most recent call last):
  File ".../sdcm/tester.py", line 182, in wrapper
    return method(*args, **kwargs)
  File ".../sdcm/utils/decorators.py", line 119, in inner
    res = func(*args, **kwargs)
  File ".../sdcm/tester.py", line 895, in setUp
    self.init_resources()
  File ".../sdcm/tester.py", line 1846, in init_resources
    self.get_cluster_aws(loader_info=loader_info, db_info=db_info,
  File ".../sdcm/tester.py", line 1327, in get_cluster_aws
    init_db_info_from_params(db_info, params=self.params, regions=regions)
  File ".../sdcm/utils/aws_utils.py", line 252, in init_db_info_from_params
    root_device = root_device if root_device else ec2_ami_get_root_device_name(
  File ".../sdcm/utils/aws_utils.py", line 417, in ec2_ami_get_root_device_name
    if image.root_device_name:
  File ".../boto3/resources/factory.py", line 386, in property_loader
    return self.meta.data.get(name)
AttributeError: 'NoneType' object has no attribute 'get'
```

Fixes: #7500