fix(hydra): improve integration with podman
The script that launches hydra doesn't work with podman:

    Error: crun: chown `/dev/pts/16`: Operation not permitted: OCI permission denied

It turns out the problem is passing /dev. Fix that by only passing /dev if
the container engine is docker.