fix(longevity_test): Set ignore raft topology connection close error globally
Error: 'raft_topology - topology change coordinator fiber got error  (connection is closed))'
Could appeared in different moment when node/nodes are being restarted.
As described in issue: scylladb/scylladb#20950 in comment:
https://github.com/scylladb/scylladb/issues/20950#issuecomment-2411387784

the error message could appeared while we have race between raft and gossip.
we can ignore this issue while issue will not be fixed on scylla side,
gossip mode will be removed from scylla.