improvement(siren-tests): print exc info when cluster_cloud import fails
For the moment, if we have some problem that breaks possibility
to import "cluster_cloud" module installed from "siren-tests" then
we do not see the reason. Error message gets suppressed by try-block.
So, catch import error message and use it when we use siren-tests.

Without this change we had this:

    ImportError: cluster_cloud isn't installed

With this change we have this:

    ImportError: cluster_cloud isn't installed. \
        No module named 'sdcm.utils.prepare_region'