fix(k8s-gke): set AZ explicitely as non-'a' for the 'us-east1' region
After merge of the 'MultiDC support for GKE backend' PR [1] the SCT
started respecting the 'availability_zone' config option.
It led to the situation that we started getting following error:

  ERROR: (gcloud.container.clusters.create) ResponseError: \
    code=400, \
    message=Specified location "us-east1-a" is not a valid zone \
      in the cluster's region "us-east1".

It is caused by the fact that the default AZ was 'a' and it is absent in
the 'us-east1' region.

So, fix this situation by explicitely setting the AZ for the GKE jobs.

[1] https://github.com/scylladb/scylla-cluster-tests/pull/6853