fix(sct_config): make .get(None) work
Since a recent change in instance profiles, we are doing calls of
`params.get(None)`, assuming it would work like a regular dict
and would return None, but it was failing like this:

```
File ".../instance_parameters_builder.py", line 74, in IamInstanceProfile
   if profile := self.params.get(self._INSTANCE_PROFILE_PARAM_NAME):
File ".../sdcm/sct_config.py", line 1808, in get
   if '.' in key:
TypeError: argument of type 'NoneType' is not iterable
```

(cherry picked from commit a5f0e366b804ee9fd76075405252dbf0967cf1f6)