fix(50gb-3days-ebs-gp3): don't use multi line in test_config
seem like our groovy pipeline are not handling correctly
`test_config` if it has multiple lines

and that's breaks the test like the following:

```
anyconfig.common.errors.UnknownFileTypeError: No parser found for file: file extension=yaml"]
```