fix(nemesis): get bytes total for correct network device
If test runs with 2 network interfaces configuration, 'disrupt_network_random_interruptions'
nemesis fails with error:
File '/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py', line 3376, in
get_rate_limit_for_network_disruption
return '{}{}'.format(random.randrange(min_limit, max_limit), rate_limit_suffix)
ValueError: empty range for randrange() (0, 0, 0)

It happened because 'node_network_receive_bytes_total' is reported on device that
broadcast_address is configured on it.
Now the device is set hardcoded to 'eth0'

(cherry picked from commit c6db2a484e23b6df18af37723781de94a4d9ba2e)

# Conflicts:
#	sdcm/cluster.py
#	sdcm/cluster_aws.py
#	sdcm/provision/network_configuration.py
#	unit_tests/test_scylla_yaml_builders.py