fix(nemesis): make argus correctly save end nemesis info after DB shrink
The decommission operation in nemesis code assigns the
'nemesis.target_node' attr with the `None` value.
It leads to the following error:

    > Traceback (most recent call last):
    >   File "%path%/sdcm/nemesis.py", line 5151, in argus_finalize_nemesis_info
    >     argus_client = nemesis.target_node.test_config.argus_client()
    > AttributeError: 'NoneType' object has no attribute 'test_config'

So, avoid this problem by getting argus client without target node.

(cherry picked from commit 6f99bd7dfef34caadf178a651aa0b6967284e598)