fix(report template): rendering of results_upgrade.html failed
Error: inja2.exceptions.TemplateSyntaxError: unexpected '}'

 Also small adjustment in results_issue_template.html

(cherry picked from commit 19cee729ed7e63a0538523e7fc4ea142c58d350c)