fix(double_cluster): stress command was waited incorrectly
nemesis case was calling `_nemesis_stress_failure_handler` with
the wrong arguments, hence failing like:

```
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5688, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4384, in disrupt_grow_shrink_cluster
self._double_cluster_load(duration)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 224, in wrapped
res = func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4370, in _double_cluster_load
self._nemesis_stress_failure_handler(results, errors)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 2139, in _nemesis_stress_failure_handler
if len(errors) == len(stress_pool.get_results()):
AttributeError: 'list' object has no attribute 'get_results'
```

this commit change it to be used as a callback to `verify_stress_thread` call.
as `_nemesis_stress_failure_handler` was designed.

Fixes: #10523
Ref: #10335