fix(gradual): run post_prepare_cql_cmds after prepare
Prepare does not run during write load. So 'keyspace1' keyspace does not exist.
It caused to failure of speculative_retry disable script.
Error: 'Keyspace keyspace1 does not exist'.
Start post_prepare_cql_cmds after prepare load only

(cherry picked from commit d34364c5f3518b36e1898f72488456384086bdc1)