improvement(cluster): filter out keyspace by replication factor
There are Scylla operation that cannot be performed on table with RF one.
This commit adds filtering out of all keyspaces with RF one to prevent this nemesis run.

The 'toggle_table_gc_mode' nemesis cannot be run on table with RF = 1 and fails with error:
ConfigurationException: tombstone_gc option with mode = repair not supported for table with RF
one or local replication strategy

If all tables are with RF 1, this nemesis should not be started

(cherry picked from commit ff1140673709c57bbbcd62203ee918a2b882b6a8)