fix(gke): properly set monitoring node labels
If we run a test on GKE backend then we get following error
creating monitoring node:

    sdcm.cluster.NodeError: Timeout while running 'ex_set_node_labels' \
        method on GCE instance '3260019724311279728'

So, fix it by adding the required 'monitorid' label to the
'tags' attribute that will be added by the common code and
remove the failing part from the GKE's monitoring class.