fix(offline-installer): remove deprecated seastar parameters
all nonroot offline installer tests failing with the following error
message:
```
error: unrecognised option '--num-io-queues=8'
```

Due to https://github.com/scylladb/scylladb/commit/4f5a460db91de59018815106abb54c1246bbb014.
one of the changes was
https://github.com/scylladb/seastar/commit/6ad997708f20636a2e8394c83165cf0009d7b77e

Since `num-io-queues` is on longer available it should be removed