fix(artifact ami test): not remove scylla data dir during scylla_image_setup
Artifact ami test failed during scylla_image_setup with error:
ValueError: invalid literal for int() with base 16: '/var/lib/scylla/data doesnot
exist - skipping\n000000ff'

In the master branch only files under data folder are removed.
Change 'clean_scylla_data' function accordingly

(Failed job)[https://jenkins.scylladb.com/job/enterprise-2020.1/job/artifacts/job/
artifacts-ami-test/411/console]