fix(sct.py): `list_ami_branch` more resilient
when running few `hydra` commands, seen failures:
```
Traceback (most recent call last):
  File "/home/fabio/git/scylla-cluster-tests/./sct.py", line 1411, in <module>
    cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/fabio/git/scylla-cluster-tests/./sct.py", line 509, in list_ami_branch
    tbl.add_row([ami.name, ami.image_id, ami.creation_date, tags['build-id'], test_status])
KeyError: 'build-id'
```

it happens, because old AMIs had different tag than
the newer ones (it will only happen when running
`<branch>:all`.

but the fix is small, and harmless in most cases, hence
submitting it.