fix(ldap-init): do not run ldap code if ldap is disabled
Recently merged refactor of the LDAP init [1] broke the K8S deployment.
Following error gets raised:

    AttributeError: 'dict' object has no attribute 'authenticator'

The reason for it is that new context manager called 'temp_authenticator'
gets run always.
This context manager does 2 restarts of the first node.
At first, it is redundant in most of the cases.
At second, it is not compatible with the K8S deployment.

So, make the new context manager be called only if it is needed.

[1] https://github.com/scylladb/scylla-cluster-tests/pull/4705