fix(nemesis): Skipping few nemesis for Sirenada run
* Skip on `RefreshMonkey` and `RefreshBigMonkey`, because the run is failed with following error:
```
validate_resharding_after_refresh(resharding_done)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 898, in
   validate_resharding_after_refresh
assert resharding_done, "Resharding wasn't run"
AssertionError: Resharding wasn't run
```
* Skipping on nemesis `TerminateAndRemoveNodeMonkey` because is not work for Scylla version `2020`

* Trello tasks: https://trello.com/c/3JAKFsjs https://trello.com/c/naxj226V/