fix(unit-test): update TestBaseVersion.test_master to be 5.4
Recent Scylla got new branch - 5.4
So, it became 'master' version which caused our
'TestBaseVersion.test_master' unit test to fail with the following
error:

  AssertionError: Lists differ: ['5.4'] != ['5.3']

So, fix it by making the test expect the '5.4' version.