fix(certificate_builder): handle dynamic client encryption state changes
Sometimes, the client encryption settings may change during the test
(we have such checks in Manager suite `test_client_encryption`).

With previous solution, it was not possible to disable encryption using
db_cluster.disable_client_encrypt method since client_encryption_options
was returning None. Now, the property would explicitly return enabled =
False in such case.

DummyNode class used in unittests enriched with is_client_encrypt
property to avoid test_scylla_yaml_builders failures due to
`AttributeError: 'NoneType' object has no attribute 'stdout'`