fix(check_latency_during_ops): build histogram data ony when needed
When running tests where we don't want to store stats (e.g.
`features-limit-streaming-io-test`), histogram data generation code
fails with error:
```
workload = self._test_index.split("-")[-1]
AttributeError: 'NoneType' object has no attribute 'split'
```
It looks that this code is needed only when `self.create_stats` is
`True`.

Fix by running histogram generation exec code only when needed.

(cherry picked from commit 100adec8e9afdfbbf0adb0d11f12e2242fc62868)