fix(sct_ssh): fix `UnboundLocalError` in `hydra attach-test-sg`
the new support for Azure we missing some variable definition

and was failing like this:
```
UnboundLocalError: local variable 'azure_vms' referenced before assignment
```

this change is setting this variable upfront with empty list