fix(check_regression_with_subtest_baseline): use use_wide_query=True
alternator perf jobs was failing to generate the report with the
following error
```
elasticsearch.exceptions.RequestError: RequestError(400,
'search_phase_execution_exception', 'failed to create query: field
expansion for [*] matches too many fields, limit: 1024, got: 2748')
```

removing the multiple matches to the `job_name` using `use_wide_query`
flag fixed the issue.

(cherry picked from commit 22f36cc812ba625fad5fef22c41c2fb6a4ce35c4)