fix(Nemesis.add_node): support using `use_preinstalled_scylla: false`
since is_replacement_by_host_id_supported is called  before starting a node,
and in `use_preinstalled_scylla: false` case scylla is not yet installed,
we should check other running nodes for version

if we don't, we'll fail with a `None` version:

```
ValueError: Cannot parse provided 'None' scylla_version for the comparison.
Transformed scylla_version:
```

Fix: #6591