_run_nodetool: fix NameError
NameError: global name 'details' is not defined
This issue was introduced by commit dd716c863ad3cf4cba1899a3ec3f500ec6150198

Signed-off-by: Amos Kong <amos@scylladb.com>