fix(azure): fix getting private DNS name for Azure VMs
After merge of the SCT#11735 PR we started getting following kind of
errors:

  Traceback (most recent call last):
    File "<path-to>/sdcm/utils/net.py", line 47, in resolve_ip_to_dns
      return socket.gethostbyaddr(ip_address)[0]
  socket.herror: [Errno 1] Unknown host
  During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
    File "<path-to>/sdcm/cluster.py", line 4030, in node_setup
      cl_inst.node_setup(_node, **setup_kwargs)
    File "<path-to>/sdcm/cluster.py", line 4871, in node_setup
      node.create_node_certificate(cert_file=node.ssl_conf_dir / TLSAssets.DB_CERT,
    File "<path-to>/sdcm/cluster.py", line 1844, in create_node_certificate
      dns_names=[self.public_dns_name, self.private_dns_name])
    File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
      val = self.func(instance)
    File "<path-to>/sdcm/cluster_azure.py", line 189, in private_dns_name
      return resolve_ip_to_dns(self.private_ip_address)
    File "<path-to>/sdcm/utils/net.py", line 49, in resolve_ip_to_dns
      raise ValueError(f"Unable to resolve IP: {e}")
  ValueError: Unable to resolve IP: [Errno 1] Unknown host

So, do following changes to mitigate it:
- Add Azure-based DNS server to the list of DNS servers.
- Try to generate the private DNS name in case private IP address failed
  to be resolved into a private DNS name.
- Print IP address that failed to be resolved for case it is empty
  value or some other value error.

Closes: https://github.com/scylladb/scylla-cluster-tests/issues/11785