fix(fill_db_data.py): fix a typo
Error: Only expressions of the form X = X +<value> are supported.

Signed-off-by: Amos Kong <amos@scylladb.com>
(cherry picked from commit ea2458f22c76e095c27081c5e0d56c273733806a)