fix(list_loadbalancers): ignore exception upon list balancers
If user doesn't have permission to api for
list aws load-balancers, sct list-resources failed
with error :
 botocore.exceptions.ClientError: An error occurred (AccessDeniedException)
  when calling the GetResources operation:
  User: arn:aws:iam::797456418907:user/alex.bykov is not authorized to perform:
  tag:GetResources because no identity-based policy allows the tag:GetResources action
  and don't show all resources.

Set ignore exception for list-loadbalancers