use --skip-broken when 'yum update -y'
to avoid env issue like:

--> Processing Dependency: /sbin/new-kernel-pkg for package: kernel-4.9.17-8.31.amzn1.x86_64
--> Finished Dependency Resolution
Error: Package: kernel-4.9.17-8.31.amzn1.x86_64 (@amzn-main)
           Requires: /sbin/new-kernel-pkg
           Removing: grubby-8.28-17.el7.x86_64 (@base)
               Not found
           Updated By: grubby-8.28-21.el7_3.x86_64 (updates)
               Not found
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest