fix(stress_thread): stop assuming current path
cause code assumed HDR to be located on `$HOME`, in some situations
like in the intergation tests of c-s, it wasn't finding it and failing
like the following:

```
FAILED unit_tests/test_cassandra_stress_thread.py::test_01_cassandra_stress -
       invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'cp cs-hdr-write-l1-c0-k1-4bf4051d-abc0-4c0d-840d-f0af5c6b6e8a.hdr
          /home/ubuntu/scylla-cluster-tests/unit_tests/
          cs-hdr-write-l1-c0-k1-4bf4051d-abc0-4c0d-840d-f0af5c6b6e8a.hdr'
Exit code: 1

Stdout:

Stderr:

cp: cannot stat 'cs-hdr-write-l1-c0-k1-4bf4051d-abc0-4c0d-840d-f0af5c6b6e8a.hdr': No such file or directory
```

(cherry picked from commit da6e8bb879cdf7ab2fd765197cf529f6b8977230)