fix(kubernetes): define KUBECONFIG running cleanup resources
Needed at least by 'gcloud' when deleting GKE clusters.

Without it we get following error during above operation:

    ERROR: (gcloud.container.clusters.delete)
        Could not create directory [/~/.kube]: Permission denied.

(cherry picked from commit 3d0957f32851fe540619da092d4c8bb798a10eb0)