fix(manager-installation): using correct paramter for GCE region
Fixes exception:    region = self.params.get('region_name').split()
AttributeError: 'NoneType' object has no attribute 'split'

(cherry picked from commit 2e470691a930b91e0b97b0c860a831ab2be12885)