fix(get_branched_repo): handle properly the source available versions
It is needed when we specify versions like "branch-2025.3:latest".
Without this fix we get following error:

  Traceback (most recent call last):
    File "<path-to>/sdcm/tester.py", line 195, in wrapper
      return method(*args, **kwargs)
    File "<path-to>/sdcm/utils/decorators.py", line 122, in inner
      res = func(*args, **kwargs)
    File "<path-to>/sdcm/tester.py", line 875, in setUp
      self._init_params()
    File "<path-to>/sdcm/tester.py", line 693, in _init_params
      self.params = init_and_verify_sct_config()
    File "<path-to>/sdcm/sct_config.py", line 2974, in init_and_verify_sct_config
      sct_config = SCTConfiguration()
    File "<path-to>/sdcm/sct_config.py", line 2031, in __init__
      self['scylla_repo'] = find_scylla_repo(scylla_version, dist_type, dist_version)
    File "<path-to>/sdcm/utils/version_utils.py", line 821, in find_scylla_repo
      raise ValueError(f"repo for scylla version {scylla_version} wasn't found")
  ValueError: repo for scylla version branch-2025.3:latest wasn't found

(cherry picked from commit 3c172e7f1c8f744cf884c1e84ae0e185ba3a3aa7)