improvement(sct-runner): add retries for checking SSH connectivity
It may happen that one of SSH attempts may fail due to various reasons.
So, add several retries to workaround following situation:

  Verifying SSH connectivity...
  Connected (version 2.0, client OpenSSH_9.6p1)
  Authentication (publickey) successful!
  Connected (version 2.0, client OpenSSH_9.6p1)
  Authentication (publickey) failed.
  Authentication failed.
  ...
  paramiko.ssh_exception.AuthenticationException: Authentication failed.