fix(k8s): don't check packages repos in sct_config module running on K8S
For the moment, when we specify 'new_version' option value the
'sct_config' module assumes we use common VMs approach and performs
checks for it.
But, at first, it is not needed in case of K8S.
And, in second, it fails when we set there too new docker image whose
version is not yet covered by AMIs or Scylla repos.

So, add check for 'K8S' to avoid following error:

    >   File "%path%/sdcm/tester.py", line 610, in _init_params
    >     self.params = init_and_verify_sct_config()
    >   File "%path%/sdcm/sct_config.py", line 2233, in init_and_verify_sct_config
    >     sct_config = SCTConfiguration()
    >   File "%path%/sdcm/sct_config.py", line 1710, in __init__
    >     self['new_scylla_repo'] = find_scylla_repo(new_scylla_version, dist_type, dist_version)
    >   File "%path%/sdcm/utils/common.py", line 1619, in find_scylla_repo
    >     raise ValueError(f"repo for scylla version {scylla_version} wasn't found")
    > ValueError: repo for scylla version 5.1.2 wasn't found