fix(get_builder_by_test_id): don't list stopped builders
Since we stopped recently a few builders

`get_builder_by_test_id` started failing with this error

```
KeyError: 'PublicIpAddress'
```

stopped instances doesn't have public address, and anyhow
we shouldn't be listing them, by default.

(cherry picked from commit fe85a9619326f825ac66ff2531e5b5d2800c77d6)