fix(sct_runner): change disk type for image creation
we don't need the `Premium_LRS` managed disks for creation
of the SCT runner

it was failing with the following error:
```
azure.core.exceptions.HttpResponseError: (InvalidParameter) Requested operation cannot
be performed because the VM size Standard_D2_v4 does not support the storage account type
Premium_LRS of disk 'sct-runner-1.7-builder-eastus'. Consider updating the VM to a size
that supports Premium storage.

Code: InvalidParameter

Message: Requested operation cannot be performed because the VM size Standard_D2_v4
does not support the storage account type Premium_LRS of disk 'sct-runner-1.7-builder-eastus'.
Consider updating the VM to a size that supports Premium storage.

Target: osDisk.managedDisk.storageAccountType
```

(cherry picked from commit 9083c96b868e8c9f7d222153104c7084e40356f7)