fix(nemesis): improve user_info_encryption check on KMS nemesis
the check assumed `user_info_encryption` is always defined,
and it's not yet true for 2023.1 branch, and fails like the
following:

```
File ".../sdcm/nemesis.py", line 4150, in _enable_disable_table_encryption
user_info_encryption_enabled = scylla_yaml.user_info_encryption.get('enabled', False)
AttributeError: 'NoneType' object has no attribute 'get'
```

(cherry picked from commit 9f0f680d74819d075f57a0a2f9871e3154e25f15)