fix(loader): typo in java-8 installation
c5591e26de2c596af35326c3821620017cdc05ed introduced new
code that was failing like:

```
File ".../sdcm/cluster.py", line 4718, in node_setup
    node.remote.sudo("ln -sf /usr/lib/jvm/java-1.8.0-openjdk-
                      amd64/jre/bin/java* /etc/alternatives/java",
AttributeError: 'GCENode' object has no attribute 'remote'
```