fix(k8s): fix 'flush and reshard' nemesis for K8S
Recently merged PR (1) add support to the multiple K8S clusters
and updated the way how the 'flush and reshard' nemesis works on K8S.
For now it broken with the following error:

  Traceback (most recent call last):
  File "%path%/sdcm/nemesis.py", line 5069, in wrapper
    result = method(*args[1:], **kwargs)
  File "%path%/sdcm/nemesis.py", line 1381, in disrupt_nodetool_flush_and_reshard_on_kubernetes
    self._verify_resharding_on_k8s(current_cpus, dc_idx)
  File "%path%/sdcm/nemesis.py", line 1293, in _verify_resharding_on_k8s
    for node in reversed(qualified_nodes):
  TypeError: 'generator' object is not reversible

So, fix this typo.
Also, reduce the required number of needed Scylla cores to be 7 to
cover more instance types such as 'i3.2xlarge' and 'i4i.2xlarge'.

[1] https://github.com/scylladb/scylla-cluster-tests/pull/6773