fix(kubernetis): get device name for k8s node
After mergin of https://github.com/scylladb/scylla-cluster-tests/pull/8925
Scylla Operator EKS longevity tests started to fail with error:
AttributeError: 'NoneType' object has no attribute 'device'.
K8s tests do not support 'node.scylla_network_configuration', it is supported
by AWS only. Define 'scylla_network_configuration' for k8s and return hardcoded
'eth0' device name.

Fixes: https://github.com/scylladb/scylla-cluster-tests/pull/8925
(cherry picked from commit ef8bec643f753b972cd3b1e8373a52f5647deccd)