fix(azure): fetch offical source-available release correctly
cause of the date version of 2025.1, the code was trying to fetch the
release from the wrong repository, and fail like:

```
ValueError: Azure Image for scylla_version='2025.1' not found in eastus
```

this commit add the logic to move to the none enterprise repo as needed

(cherry picked from commit b53e26de6f38bdd6598e1f7bd534f6f287133b3f)