fix(db_stats): add retry also to `exists`
in addition to what was done on 4fd9c4f6d35770c091e7dffb7d4758e03872edf0
we need to handle also HEAD request that can get those errors:

```
elasticsearch.exceptions.TransportError: TransportError(429, '')
```