fix(get_non_system_ks_cf_list): Add missing column to cql query
filtering table with counters uses column 'type' which is missing
in query

Cause an error during nemesis:
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3142, in get_non_system_ks_cf_list
regular_table_names = execute_cmd(cql_session=session, entity_type="column")
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3132, in execute_cmd
elif is_column_type and (filter_out_table_with_counter and "counter" in row.type):
AttributeError: 'Row' object has no attribute 'type'

(cherry picked from commit 7cc49b4aae75296f9d097d1dd08b4bc8e79ad884)