fix(in memory cs): InMemoryCompactionStrategy is missed in the compaction strategy enum
Test longevity-in-memory-36gb-1d-test failed in the branch-2020.1 with error:
ValueError: 'InMemoryCompactionStrategy' is not a valid CompactionStrategy
during the nemesis ToggleTableICS due to InMemoryCompactionStrategy is missed
in the compaction strategy enum.
Add this cs to enum