fix(perf-simple-query): handle 'perf_simple_query_extra_command' param
New parameter 'perf_simple_query_extra_command' was presented in
https://github.com/scylladb/scylla-cluster-tests/pull/10331

If the new parameter is not defined for the test, the 'None' is return by get and causes to test
failure:
Command: 'scylla perf-simple-query --json-result=perf-simple-query-result.txt --smp 1 -m 1G None'
error: too many positional options have been specified on the command line

Return empty string instead of 'None'.