fix(test_user_batch_custom_time): handle stress command correctly
seems like we were running into situations we try to add all nodes ips into
stress commands, and it's the test code
```
File ".../longevity_test.py", line 300, in test_user_batch_custom_time
self._run_user_stress_in_batches(batch_size=batch_size,
File ".../longevity_test.py", line 336, in _run_user_stress_in_batches
batch_params['stress_cmd'] += [params['stress_cmd'] + nodes_ips]
TypeError: list indices must be integers or slices, not str
```

in this change remove a parentheses that was causing function to return
tuple and not string as expected

(cherry picked from commit 8f16d05ae5438cb26d3c199ce0419c7e546de375)