fix(k8s-minikube): install prerequisites correctly
Do following fixes:
- Separate docker installation from other prerequisites installation
  such as installation fo required 'conntrack' package.
- Add creation of /etc/ssh/ssh_host_ecdsa_key if it is absent.
  It is needed at least for the minikube and installation of scylla
  for manager service.
- Remove usage of 'change_context=True' arg in 'node.remoter.sudo()'
  method, because it just doesn't have it.
  'LocalCmdRunner' class is different than the one used for remote
  sudo calls.
  Error that exists not fixing it:

      TypeError: sudo() got an unexpected keyword argument \
          'change_context'

  This error happens when some prerequisite is not installed.
  So, local K8S works for people who already have correct requirements
  setting.
- Add also possibility to run tests on 'debian', not only 'ubuntu'.
  Prerequisites code must work on both.