fix(sct-runner): use public addresses for sct-runner cleanups
since now we have region with no bastions (i.e. no permenent
jenkins workers), we can do direct connection via public address
without proxy

other wise we'll get this error:
```
AssertionError: No bastion found for region: ca-central-1
```