fix(defaults): add missing default for 'latte_schema_parameters' option
Recent latte feature implementation missed adding a default parameter,
namely:
    latte_schema_parameters: {}

causing SCT tests fail with the following error message:
    File "/home/ubuntu/scylla-cluster-tests/sdcm/stress/latte_thread.py", line 142, in build_stress_cmd
    if latte_schema_parameters := self.params['latte_schema_parameters']:
    KeyError: 'latte_schema_parameters'

The patch adds the missing parameter to defaults/test_default.yaml

(cherry picked from commit 5d767ce58a70fb3a3c4485f6a7717fdbb5d7b3ac)