fix(k8s): make raft checks work on K8S
Due to the K8S specifics we do not use the 'ScyllaYaml' class.
So, when common code assumes we use it we get the following error:

    'dict' object has no attribute 'consistent_cluster_management'

The reason for it is that we use completely different approach in K8S.
So, fix the newly introduced raft handling code [1] to work with K8S.

[1] https://github.com/scylladb/scylla-cluster-tests/pull/6015

(cherry picked from commit 7b32a80a925592a0c8d075224829b8e5b44b4d15)