fix(artifacts test): move additional config to configurations directory
Currently the linting unit-tests failed in config.verify_configuration(),
it doesn't find required parameter in the additional config files of
ARM artifacts-test. This patch moved the additional config files to
configurations directory.

---- linting: ./test-cases/artifacts/arm/centos8.yaml -----
Traceback (most recent call last):
  File "/jenkins/slave/workspace/scan_scylla-cluster-tests_master/./sct.py",
  line 463, in _run_yaml_test
    config.verify_configuration()
AssertionError: user_prefix missing from config for gce

Signed-off-by: Amos Kong <amos@scylladb.com>