fix(arm-centos8): replace deprecated ARM image
the image we were using seem to be deprated and don't
show on console, and don't have it's metadata available
anymore failing like:
```
  if not ami_built_by_scylla(ami_id, region_name):
File ".../sdcm/utils/common.py", line 2028, in ami_built_by_scylla
  return image.owner_id == SCYLLA_AMI_OWNER_ID
File "../boto3/resources/factory.py", line 386, in property_loader
  return self.meta.data.get(name)
AttributeError: 'NoneType' object has no attribute 'get'
```

updated form a fresh image taken from:
https://www.centos.org/download/aws-images/

(cherry picked from commit b3912362361f2067e9d5ccd3e4a6c4ee6d7ffdad)