fix(nemesis): disrupt_modify_table failure
It is allowed that compaction strategy has only 'class' defined, and 'compaction_window_size' and
'compaction_window_unit' are not defined. Like:
compaction = {'class': 'TimeWindowCompactionStrategy'}

In this case the nemesis fails with error:
KeyError: 'compaction_window_unit'

Example of failed test:
https://argus.scylladb.com/test/079cddb4-4eac-4594-a2f0-8452dab5eb40/runs?additionalRuns[]=
73ec8004-3881-4cbb-b37b-11c75c1c1126

(cherry picked from commit d5cf38889b25dcd14db3c99def1cf3579a96a14d)