fix(tests): increase root disk size for integration tests
We happen to get the following error running integration tests in CI:

  OSError: [Errno 28] No space left on device

So, fix it by specifying bigger root disk size for integration tests.

(cherry picked from commit b2330f9e9431bb12fcc7b8c756fe0f1624fb33c0)