fix(raft): generator was not correctly implemented in check_group0_tokenring_consistency
After running `gemini` inside SCT
- https://jenkins.scylladb.com/job/scylla-staging/job/dusan/job/gemini/job/gemini-1tb-10h-test/12/

Command for the test never ran and SCT fails with.

TypeError: 'NoneType' object is not iterable'.

With some investigation it came down to
sdcm/utils/raft/__init__.py::NoRaft implementation ignored to implement
`Generator`, used `return` instead of `yield`

Signed-off-by: Dusan Malusev <dusan.malusev@scylladb.com>
(cherry picked from commit d7ad4c87aa9543aca656daa46083806e728574f3)