fix(byolongevity): delete pipelineParams from byolongevity
byolongevity pipeline doesn't support pipelineParams parameter
 and cause issue:
hudson.remoting.ProxyException: groovy.lang.MissingPropertyException:
 No such property: pipelineParams for class: byoLongevityPipeline
   at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)