fix(parse_scylla_version): better check the version
it was failing like:
```
File ".../sdcm/fill_db_data.py", line 3173, in version_non_frozen_udt_support
return self.parsed_scylla_version >= parse_scylla_version(version_with_support)
File ".../sdcm/utils/version_utils.py", line 123, in parse_scylla_version
return parse_version(version_format.search(version_to_parse)[0])
TypeError: 'NoneType' object is not subscriptable
```

since the version passed to is was not matching the regex

```python
NON_FROZEN_SUPPORT_ENTERPRISE_MIN_VERSION = '2020'
```

now it checking it better and rasining clear exception why it was
failing