fix(db node): return scylla_shard as int always
scylla_shards may return string instead of integer value. It cause to failure with error like:

TypeError: '>' not supported between instances of 'str' and 'int'

This property may receive the shards value from 3 different properties: cpu_cores, smp or cpuset.
Every this property is used by different functions. So to decrease the impact of this fix,
the shards value will be converted inside scylla_shards property, not in every property.

Fixes: https://github.com/scylladb/scylla-cluster-tests/issues/6562
(cherry picked from commit a57c8ce3445ba2757b1966bbe3a76f136de4aeb8)