fix(k8s-mgmt): make backup work using mgmt-3.0
We should not have spaces in the name of backup to avoid following
errors:

    $ sctool -c %uuid% progress backup/Default backup task name
    Error: accepts 1 arg(s), received 4

(cherry picked from commit 4bf38fd22b1d7fe997894cc3a48e67fe8cc0bd7a)