fix(k8s-eks): fix EKS iamserviceaccout creation on multitenant setups
After merge of the PR [1] with the S3 usage in EKS deployments all our
multitenant setups on this backend started failing the following way:

  Error: failed to create iamserviceaccount(s)

It is caused by the fact that there was attempt to create
an iamserviceaccount per tenant. But it must be done only per K8S
cluster.

So, fix it by calling the appropriate function just once per K8S
cluster.

[1] https://github.com/scylladb/scylla-cluster-tests/pull/7088