fix(test_classes): switch from `__init__` to `setUp`
following 32ebb721422788c0978f202c9494669ab3aee101, seems like we didn't
changed all of the test classes using this pattern.

this commit cover all of this class that still were using `__init__`

one that did, was failing like the following:
```
AttributeError: 'TombstoneGcLongevityTest' object has no attribute 'params'
```