fix(Compaction): remove InMemoryCompactionStrategy
Deleted InMemoryCompactionStrategy from SCT
due to feature removed from scylla-enterprise and now we have an error:
ConfigurationException: InMemoryCompactionStrategy has been deprecated.