fix(upgrade_test): index for sla role should be int
Upgrade test with sla failed, because index pass to
function creating Role as str, while it expected int.

File "/home/ubuntu/scylla-cluster-tests/test_lib/sla.py", line 357, in create_sla_auth
role = Role(session=session, name=STRESS_ROLE_NAME_TEMPLATE % (shares or '', index),
TypeError: %d format: a real number is required, not str