fix(cluster.py): make run_nodetool not raise TypeError
If 'self.ssh_login_info' is None in the 'run_nodetool' method then
we get following error:

    TypeError: unsupported operand type(s) for |: 'NoneType' and 'dict'

It may be empty in case of common VMs deployments and always empty
running on K8S.

So, fix it by using variables more safely.