fix(nemesis): fix typo in disrupt_add_remove_dc
b5808cefa7f91f5202ec65ac2f72694a97b246f7 fix introduced
extra parentheses in one of the regex to look for

it was breaking the test like this:

```
Traceback (most recent call last):
File ".../sdcm/nemesis.py", line 5062, in wrapper
result = method(*args[1:], **kwargs)
File ".../sdcm/nemesis.py", line 4488, in disrupt_add_remove_dc
with wait_for_log_lines(node=new_node,
   start_line_patterns=["rebuild.*started with keyspaces=", "Rebuild starts"],
File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
return next(self.gen)
File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 144, in wait_for_log_lines
end_follower = node.follow_system_log(patterns=end_line_patterns)
File ".../sdcm/cluster.py", line 1383, in follow_system_log
regexps.append(re.compile(pattern, flags=re.IGNORECASE))
File "/usr/local/lib/python3.10/re.py", line 251, in compile
return _compile(pattern, flags)
File "/usr/local/lib/python3.10/re.py", line 303, in _compile
p = sre_compile.compile(pattern, flags)
File "/usr/local/lib/python3.10/sre_compile.py", line 788, in compile
p = sre_parse.parse(p, flags)
File "/usr/local/lib/python3.10/sre_parse.py", line 955, in parse
p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
File "/usr/local/lib/python3.10/sre_parse.py", line 444, in _parse_sub
itemsappend(_parse(source, state, verbose, nested + 1,
File "/usr/local/lib/python3.10/sre_parse.py", line 843, in _parse
raise source.error("missing ), unterminated subpattern",
re.error: missing ), unterminated subpattern at position 0
```

(cherry picked from commit 63d11c1197ef89c82cc97c7803af5eda58e1ceec)