fix(k8s-stress): make 'run_stress_thread' work on K8S
After merge of [1] we get following error running any test which calls
'run_stress_thread' method of the 'tester' class instance:

    >   File "scylla-cluster-tests/sdcm/cluster_k8s/__init__.py", \
    >       line 2130, in wait_for_nodes_up_and_normal
    >     self.wait_for_pods_readiness(\
    >       pods_to_wait=len(nodes), total_pods=len(self.nodes))
    > TypeError: object of type 'NoneType' has no len()

The reason for it is unsafe coding of the K8S' part.
So, make it be safe enough by replacing 'None' with 'empty list' before
calling 'len()' function.

[1] https://github.com/scylladb/scylla-cluster-tests/pull/4610