fix(results_analyze.get_events): Set correct variable type
When getting events during prepare email report for performance
tests with compared results, next error happened:
Traceback (most recent call last):
File: sdcm/tester.py", line 2461, in check_regression
results_analyzer.check_regression(self._test_id, is_gce,
File "sdcm/results_analyze/__init__.py", line 576, in check_regression
last_events, events_summary = self.get_events()
File "sdcm/results_analyze/__init__.py", line 116, in get_events
     event_severity.append(event.name)
AttributeError: 'NoneType' object has no attribute 'append'

(cherry picked from commit 41a6bbff14a26047cd29f68507fe20c6195105c6)