fix(wait_for): stop using `tenacity.RetryError`
`tenacity.RetryError` get a future as parameter, and SCT was
passing a string to it's `__init__`

causing this failure in cases of casscading `wait_for` calls:

```
res = retry(func, **kwargs)
except Exception as ex:  # pylint: disable=broad-except
err = f"Wait for: {text or func.__name__}: timeout - {timeout} seconds - expired"
LOGGER.error(err)
>           if hasattr(ex, 'last_attempt') and ex.last_attempt.exception() is not None:
E           AttributeError: 'str' object has no attribute 'exception'
```