fix(test_default): Add default value for gce_pd_standard_disk_size_db
job: scylla-master/longevity/longevity-100gb-4h-test#462,
failed:
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3511, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4210, in node_setup
if self.is_additional_data_volume_used():
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4470, in is_additional_data_volume_used
return self.params.get("data_volume_disk_num") > 0 or self.params.get('gce_pd_standard_disk_size_db') > 0
TypeError: '>' not supported between instances of 'NoneType' and 'int'

it happened because gce_pd_standard_disk_size_db is not defined for aws job.

(cherry picked from commit 7eb9fadb2057d41f99552ed6c129924ad1b82009)