fix(sct_runner): overwrite connect_timeout, 60s wasn't enough
even that we pass down `timeout=100` the `connect_timeout` default to
60s, and since it's a newly created machine, it's not always enoguh
time for it to be ready and available.

```
File "./sct.py", line 812, in create_runner_instance
   result = remoter.run("true", timeout=100, verbose=False, ignore_status=True)
File ".../sdcm/remote/remote_base.py", line 601, in run
   result = _run()
File ".../sdcm/utils/decorators.py", line 61, in inner
   return func(*args, **kwargs)
File ".../sdcm/remote/remote_base.py", line 591, in _run
   self._run_pre_run(cmd, timeout, ignore_status, verbose, new_session, log_file, retry, watchers)
File ".../sdcm/remote/remote_cmd_runner.py", line 106, in _run_pre_run
   raise SSHConnectTimeoutError(
sdcm.remote.base.SSHConnectTimeoutError: Unable to run "true":
failed connecting to "3.234.207.111" during 60s
```