fix(unit-test): skip the TestBaseVersion.test_2025_1_release_centos test
The 'TestBaseVersion.test_2025_1_release_centos' requires zstd support.
But it is absent in this branch and we get following error:

  FileNotFoundError: [Errno 2] No such file or directory: 'zstd'

So, skip this test to unblock CI.