fix(sct-runner-usage): allow SCT_RUNNER_IP env var to be set
To avoid following error:

    ValueError: Unsupported environment variables were used:
     - SCT_RUNNER_IP=34.138.242.64

Such error started appearing after merge of the following PR:
- https://github.com/scylladb/scylla-cluster-tests/pull/3901

Where previously local env var called "SCT_RUNNER_IP" started
being exported.