fix(artifact-arm-centos8): update the base image
Since the image we used seems to be deleted from AWS, and
we were getting the following error:

```
   File ".../sdcm/utils/aws_utils.py", line 359, in ec2_ami_get_root_device_name
     if image.root_device_name:
   File ".../boto3/resources/factory.py", line 386, in property_loader
     return self.meta.data.get(name)
 AttributeError: 'NoneType' object has no attribute 'get'
```

(cherry picked from commit 370e8a0230bcb7e48b72fddf324ceabde1e3432a)