feature(run-test): make sure we don't select multiple test methods
Since SCT is built on running only one test method, we should
be more clear about and fail early on, if user by mistake selected
more then one test method

now we he does that, this is the error that would be presented:
```
AssertionError: SCT expect only one test case to be selected, found 3:
['test_batch_custom_time', 'test_custom_time', 'test_user_batch_custom_time']
```

Fixes: #4840