fix(nodetool): workaround wrong placement of cassandra-rackdc.properties
Operator upgrade job fails with following error:
    WARN  13:58:44,341 Unable to read cassandra-rackdc.properties
    error: DC or rack not found in snitch properties,
    check your configuration in: cassandra-rackdc.properties
Using scylla 4.4.1 docker image on K8S backends.

So, workaround it by copying 'cassandra-rackdc.properties' file
to "/etc/scylla/cassandra" dir.

(cherry picked from commit f87e8c7ec371c631f92a1a6b0fad600b0c40f260)