fix(aws-provision): have a default for `user_data_format_version`
since we don't set a default for `user_data_format_version` in case
we are using images which are not scylla for the db nodes

we'll be hitting the following error in provision step:

```
pydantic.error_wrappers.ValidationError: 1 validation error for ScyllaUserDataBuilder
user_data_format_version
  none is not an allowed value (type=type_error.none.not_allowed)
```

in all other backend we have default for this value, and in AWS we were missing it,
it's only affecting once case we have that is running longevity without scylla images.

(cherry picked from commit f2c93cc24982c5d63aab47d951b6bfe9a07cb6c1)