AWS: move `self._wait_public_ip()` back to before `super()` (#1498)
Was causing `self.public_address` to return None
and failing the cluster setup like that, when trying to initalize
the ssh connection:

```
 Traceback (most recent call last):
   File "/sct/sdcm/tester.py", line 134, in wrapper
     return method(*args, **kwargs)
   File "/sct/sdcm/utils/common.py", line 136, in inner
     res = func(*args, **kwargs)
   File "/sct/sdcm/tester.py", line 258, in setUp
     self.init_resources()
   File "/sct/sdcm/tester.py", line 797, in init_resources
     monitor_info=monitor_info)
   File "/sct/sdcm/tester.py", line 618, in get_cluster_aws
     self.db_cluster = create_cluster(db_type)
   File "/sct/sdcm/tester.py", line 584, in create_cluster
     **cl_params)
   File "/sct/sdcm/cluster_aws.py", line 780, in __init__
     aws_extra_network_interface=params.get('aws_extra_network_interface'))
   File "/sct/sdcm/cluster.py", line 2575, in __init__
     super(BaseScyllaCluster, self).__init__(*args, **kwargs)
   File "/sct/sdcm/cluster_aws.py", line 95, in __init__
     node_type=node_type,
   File "/sct/sdcm/cluster.py", line 2373, in __init__
     self.add_nodes(num, dc_idx=dc_idx)
   File "/sct/sdcm/cluster_aws.py", line 803, in add_nodes
     enable_auto_bootstrap=enable_auto_bootstrap)
   File "/sct/sdcm/cluster_aws.py", line 385, in add_nodes
     enumerate(instances, start=self._node_index + 1)]
   File "/sct/sdcm/cluster_aws.py", line 384, in <listcomp>
     for node_index, instance in
   File "/sct/sdcm/cluster_aws.py", line 399, in _create_node
     base_logdir=base_logdir, dc_idx=dc_idx, node_type=self.node_type)
   File "/sct/sdcm/cluster_aws.py", line 429, in __init__
     dc_idx=dc_idx)
   File "/sct/sdcm/cluster.py", line 404, in __init__
     self.remoter = RemoteCmdRunner(**ssh_login_info)
   File "/sct/sdcm/remote.py", line 189, in __init__
     connect_kwargs=self.connect_config)
   File "/sct/sdcm/remote.py", line 106, in _create_connection
     self.connection = Connection(*args, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 386, in __init__
     shorthand = self.derive_shorthand(host)
   File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 574, in derive_shorthand
     return derive_shorthand(host_string)
   File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 34, in derive_shorthand
     user_hostport = host_string.rsplit("@", 1)
 AttributeError: 'NoneType' object has no attribute 'rsplit'
```