fix(longevity-cdc-4h): fix datacenter name
seem like when using only one region, the name of the region
is diffrent then in multi region setup, fixing the name in
this test configuration

if failed like the following:
```
cassandra.protocol.ConfigurationException: <Error from server: code=2300
[Query invalid because of configuration issue] message="Unrecognized
strategy option {eu-westscylla_node_west} passed to org.apache.cassandra.
locator.NetworkTopologyStrategy for keyspace cdc_test">
```