fix(nemesis): remove SimpleStatement from delete_by_range_using_timestam
Commit https://github.com/scylladb/scylla-cluster-tests/pull/6450/commits/
bd9acd9ecb600c72ead5a9e181238ccf1aed7f6c presented common solution for all delete_by_range
nemeses - run delete query with CL=QUORUM by using 'SimpleStatement'.
I missed that 'SimpleStatement' is already used in 'delete_by_range_using_timestamp'.
So now it cause to query failury:
Executing CQL '<SimpleStatement query=<SimpleStatement query=delete from scylla_bench.test
using timestamp 1691403471151446 where pk = 122, consistency=Not Set>, consistency=QUORUM>' ...
Error querying host 10.0.3.12:9042 Error querying host 10.0.3.12:9042
TypeError: object of type 'SimpleStatement' has no len()