fix(pipelines): handle stress_duration correctly
a76ed862ad99c58012699546822eab08a94b2ea9 introduced a new
parameter to the longevity pipeline, but it's was breaking
all other pipelines, like:

```
java.lang.NullPointerException: Cannot invoke method toInteger() on null object
```

(cherry picked from commit 39c1fc02fe6726a8b70db3dbd6594163549a21bb)