fix(kubernetes): suppress absence of seed nodes
After merge of [1] K8S deployment started failing with following error:

    AssertionError: We should have at least one selected seed by now

The reason for it is that operator-1.4+ stopped using seed nodes and
reuses seedless approach. So, check for seeeds is not relevant to K8S
backends.
So, fix it by redefining 'seed_nodes_ips' and 'seed_nodes' properties
with empty values.

[1] https://github.com/scylladb/scylla-cluster-tests/pull/3882