fix(scylla doctor): few fixes in docker artifact test
Fixes of failures in the docker artifact test after
Scylla Doctor run:

1.
error: 'Unable to locate package wget'
Fix: update 'apt repo' before installation
Fixs: https://github.com/scylladb/scylla-cluster-tests/issues/7418

2. one collector failed due to missed 'ethtool' package - install it during
Scylla Doctor installation

3. Scylla Docker does not collect Scylla cluster logs. Skip assert of existing
'scylla_cluster.tar.gz' file

4. Ignore failure of 2 collectors: StorageConfigurationCollector and
PerftuneSystemConfigurationCollector.
Looks like it should be skipped for docker backend - issue
https://github.com/scylladb/field-engineering/issues/2288