fix(hydra): use python3.11 `Don’t prepend a potentially unsafe path to sys.path`
cause if we don't, we have some modules in utils which are identical in thier names
to some builtins, and it would fail like that:
```
Traceback (most recent call last):
  File "..././sdcm/utils/get_username.py", line 15, in <module>
    import getpass
  File ".../3.11.3/lib/python3.11/getpass.py", line 17, in <module>
    import contextlib
  File ".../3.11.3/lib/python3.11/contextlib.py", line 6, in <module>
    from collections import deque
  File ".../3.11.3/lib/python3.11/collections/__init__.py", line 36, in <module>
    from operator import eq as _eq
ImportError: cannot import name 'eq' from 'operator'
(.../sdcm/utils/operator/__init__.py)
```

this snippet of python code is run before we get into the hydra image
hence we don't control the python version being used...

(cherry picked from commit 1bffa59a96a1d09bcd8a9665a61b0135b127bfff)