fix(snapshot_operations): remove quotes from keyspaces/columnfamilies
since #7104 introduced quotes for keyspaces and column families, for usage
in CQL, but in case like this one, when it's used for comparing with outputs
other then CQL, it's was breaking the logic, like the following

```
Traceback (most recent call last):
  File ".../sdcm/nemesis.py", line 5059, in wrapper
    result = method(*args[1:], **kwargs)
  File ".../sdcm/nemesis.py", line 3200, in disrupt_snapshot_operations
    self._validate_snapshot(nodetool_cmd=nodetool_cmd, snapshot_content=snapshot_content)
  File ".../sdcm/nemesis.py", line 3098, in _validate_snapshot
    raise AssertionError(f"Snapshot content not as expected. \n"
AssertionError: Snapshot content not as expected.
Expected content: [ ... ['system', '"IndexInfo"'], ... ]
Actual snapshot content: [ ... ['system', 'IndexInfo'], ... ]
```