fix(GrowShrinkClusterNemesis): don't assume `params.get()` has default
a2d988688a1be6b69f953e1a66572a2f6736347a assumed `get()` has default
argument, and failed like this:

```
initial_db_size = self.tester.params.get("k8s_n_scylla_pods_per_cluster", initial_db_size)
TypeError: SCTConfiguration.get() takes 2 positional arguments but 3 were given
```