fix(remote_logger): Fix duplicate initialization of RemoteCMDRunner
Remove duplication initializtion of RemoteCMDRunner which cause
error:
self._remoter = self._remoter_params.pop('__class__')(**self._remoter_params)
KeyError: '__class__'

and this error don't allow to get db log