gce: fix gce_region_names
We use default 'us-east1-b' in init() of GCECluster for LoaderSetGCE,
MonitorSetGCE before commit c7f16dc. The commit c7f16dc moved the default value
assignment after self._gce_region_names assignment, so self._gce_region_names
is always None.

> Traceback (most recent call last):
>   File "/sct/sdcm/tester.py", line 134, in wrapper
>     return method(*args, **kwargs)
>   File "/sct/sdcm/utils/common.py", line 136, in inner
>     res = func(*args, **kwargs)
>   File "/sct/sdcm/tester.py", line 259, in setUp
>     self.init_resources()
>   File "/sct/sdcm/tester.py", line 808, in init_resources
>     monitor_info=monitor_info)
>   File "/sct/sdcm/tester.py", line 482, in get_cluster_gce
>     **common_params)
>   File "/sct/sdcm/cluster_gce.py", line 380, in __init__
>     params=params)
>   File "/sct/sdcm/cluster_gce.py", line 181, in __init__
>     region_names=gce_region_names)
>   File "/sct/sdcm/cluster.py", line 2346, in __init__
>     self.add_nodes(n_nodes)
>   File "/sct/sdcm/cluster_gce.py", line 310, in add_nodes
>     instances = self._create_instances(count, dc_idx)
>   File "/sct/sdcm/cluster_gce.py", line 277, in _create_instances
>     instances.append(self._create_instance(node_index, dc_idx))
>   File "/sct/sdcm/cluster_gce.py", line 249, in _create_instance
>     dc_idx=dc_idx))
>   File "/sct/sdcm/cluster_gce.py", line 208, in _get_root_disk_struct
>     "diskType": self._get_disk_url(disk_type, dc_idx=dc_idx),
>   File "/sct/sdcm/cluster_gce.py", line 199, in _get_disk_url
>     return "projects/%s/zones/%s/diskTypes/%s" % (project.name, self._gce_region_names[dc_idx], disk_type)
> TypeError: 'NoneType' object is not subscriptable

Signed-off-by: Amos Kong <amos@scylladb.com>