sct_event: TestFrameworkEvent was casing Circular reference (#1676)
since TestFrameworkEvent was passing the exception as is,
we can't pass is as ZMQ messgae or turn it to json.

and the following failure happens:

Traceback (most recent call last):
  File "/sct/sdcm/tester.py", line 127, in wrapper
    return method(*args, **kwargs)
  File "/sct/sdcm/utils/common.py", line 139, in inner
    res = func(*args, **kwargs)
  File "/sct/sdcm/tester.py", line 287, in setUp
    exception=exc
  File "/sct/sdcm/sct_events.py", line 152, in publish
    EVENTS_PROCESSES['MainDevice'].publish_event(self)
ValueError: Circular reference detected

changed the code to stringify the excption, and pass the traceback as string
also change __str__ function a bit, and added a unittest