fix(node_benchmarks): make it tolerate when some data is absent. Part 2
For now, we get following error:

    KeyError: 'cassandra_fio_lcs_64k_read'

in some cases reading data from ElasticSearch.
And the problem with it is that in some cases SCT may fail to find
data for some fields. And it leads to the incomplete set of data.
So, tolerate it instead of failing with 'KeyError' exception in one
more place - '_compare_results' method.