fix(scylla-manager): get version if monitor node exists
This issue was caused by https://github.com/scylladb/scylla-cluster-tests/pull/7538.
The monitor node is not created in artifact test that causes to failure:

File sdcm/tester.py, line 508, in argus_collect_manager_version
  manager_tool = get_scylla_manager_tool(manager_node=self.monitors.nodes[0])
  IndexError: list index out of range

(cherry picked from commit b8140c3aaa0cf9535e802e056be8db9c16cba3b3)