fix(update_repo_cache): stop calling `debconf-set-selections`
this call was add long ago for unclear reasons
probably try to make sure we won't be asked questions
during apt commands.

recently it's failing like the following:

```
error: Cannot find a question for debconf/frontend
```

while still no causing any issue for any tests,
so we going to remove this call out

Fixes: #6443