fix(alternator_perf): change isolation parameter to create_table
since b587c81b67f26d72c25aed20af3b497935161b93 the parameter
for table creation changed, otherwise we have the following error:

```
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "alternator_write_isolation", must
be one of: AttributeDefinitions, TableName, KeySchema,
LocalSecondaryIndexes, GlobalSecondaryIndexes, BillingMode,
ProvisionedThroughput, StreamSpecification, SSESpecification, Tags
```