fix(run_unique_sequence): use same target node for each step
When this nemesis runs with multidc configuration,
disrupt_mgmt_repair and disrupt_terminate_and_replace
methods could choose target node from different dc,
and _shrink_cluster method periodically failed with error:
```
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4277, in _shrink_cluster
    raise Exception(error)
Exception: Not enough nodes for decommission
```

because target_node was chosen from dc where new node was not added by
_grow_cluster method.

Additionaly set to run nemesis only for data nodes

(cherry picked from commit a8fb34a3a87d606889c51ecf8f49c73d283d20d4)