fix(cs-profiles): use user profiles located at '/tmp' be used 'as-is'
For the moment, when we use c-s user profiles in CI jobs we get
following error:

  FileNotFoundError: User profile file templated_tables_mvs3ysgyis.yaml \
    not found under /home/ubuntu/scylla-cluster-tests

The file that was attempted to be found under the SCT dir has
dynamically added suffix 's3ysgyis' and was doomed to be not found.

So, fix it by backing up the search logic by using the filepath 'as-is'.

(cherry picked from commit 3b26345e034f08f008bf1f8f51d9f0f676d7975e)