fix(nemesis): disruption event when not enough nodes for decommission
cloud-longevity-100gb-3d failed with error:
TypeError: DisruptionEvent.__init__() got an unexpected keyword argument 'type'

(cherry picked from commit 43f462988d53b603fbbba9d390592c1038205819)