fix(configuration/gce): typo in configuration filename
PR #6350 introduced new configurations
for diffrent GCE instance types, and one of them
had a typo, and was missing a char, and failing
like the following:

```
FileNotFoundError: [Errno 2] No such file or directory:
'/home/ubuntu/scylla-cluster-tests/configurations/gce/n2-highmem-8.yaml'
```