ci(oci): wait for rpm lock on rhel-based distros
Running Artifacts tests on the OCI backend may lead to the following error:

    > Command: 'sudo yum install -y scylla'
    >
    > Exit code: 1
    >
    > Stdout:
        ...
    > Error: GPG check FAILED

It is caused by the 'rpm.lock' being held by the OCI agent installation
process which starts after the DB node startup.

So, tolerate rpm.lock holdings in SCT.
Do it by adding an additional bash checker for that lock before
executing package management commands.

(cherry picked from commit 90e252b53826b98774a220faf941a9c50aa5d380)