fix(gke): allow SCT runner call GKE APIs
For the moment, if we try to create a GKE cluster we get following
error:

    ERROR: (gcloud.container.clusters.create) ResponseError: \
        code=403, message=Request had insufficient authentication scopes.

The root cause for it is absence of enabled 'cloud-platform' scope
for the SCT runner isntance.
So, fix it by specifying this scope creating GCE instance.